name: Java CI with Maven and Security Scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Set up environment variables
        env:
          GMAILD_USER_NAME: ${{ secrets.GMAILD_USER_NAME }}
          GMAILD_API_PASS: ${{ secrets.GMAILD_API_PASS }}
      - name: Build with Maven
        run: mvn clean install